### ISSUE TITLE
Scaffold Gem Documentation

### ISSUE THREAD

**Issue by ManuelAcostaGuerrero** [BC-MAY-21-ROR/kata-06-reloj-checador-k06-t05#7]
# REQUIREMENTS
We are going to do some research on the gem Scaffold, to complete the forms for employees and stores.

**Comment by xFerchoVJ** [comment]
Scaffold is a gem that generates code which allows us to have the basic management functionalities of a model, that is, the CRUD, and which are typical for any system.
